---
# Variables for [web] hosts (Nginx serving React SPA)

frontend_source_dir: "{{ app_dir }}/eCommerce-react-frontend"
frontend_web_root: /var/www/ecommerce

# The API base URL React uses at build time (points to the load balancer)
# Must be set before npm run build
frontend_api_url: "http://{{ hostvars[groups['lb'][0]]['ansible_host'] }}"
