---
- name: restart gunicorn
  systemd:
    name: ecommerce-gunicorn
    state: restarted
    daemon_reload: true

- name: reload gunicorn
  systemd:
    name: ecommerce-gunicorn
    state: reloaded

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
